apiVersion: v1
kind: Pod
metadata:
    name: nginx-with-env
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: environment
          value: "production"
      ports:
        - containerPort: 80
        