apiVersion: v1
kind: Pod
metadata:
    name: nginx-with-labels
    labels:
       app: nginx
       environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80