apiVersion: v1
kind: Pod
metadata:
    name: nginx-multiple-ports
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:  
        - containerPort: 80
        - containerPort: 443